In [1]:
import basedosdados as bd
import os
import pandas as pd
import numpy as np

In [ ]:
#query de construção da base 
query = '''
WITH saeb as (
  SELECT 
  ano,
  CAST(id_municipio AS string) AS id_municipio,
  rede,
  localizacao,
  media_lp_5,
  media_mt_5,
  media_lp_9,
  media_mt_9,
  media_lp_em,
  media_mt_em,
  nivel_0_lp_5,
  nivel_1_lp_5,
  nivel_2_lp_5,
  nivel_3_lp_5,
  nivel_4_lp_5,
  nivel_5_lp_5,
  nivel_6_lp_5,
  nivel_7_lp_5,
  nivel_8_lp_5,
  nivel_9_lp_5,
  nivel_0_mt_5,
  nivel_1_mt_5,
  nivel_2_mt_5,
  nivel_3_mt_5,
  nivel_4_mt_5,
  nivel_5_mt_5,
  nivel_6_mt_5,
  nivel_7_mt_5,
  nivel_8_mt_5,
  nivel_9_mt_5,
  nivel_10_mt_5,
  nivel_0_lp_9,
  nivel_1_lp_9,
  nivel_2_lp_9,
  nivel_3_lp_9,
  nivel_4_lp_9,
  nivel_5_lp_9,
  nivel_6_lp_9,
  nivel_7_lp_9,
  nivel_8_lp_9,
  nivel_0_mt_9,
  nivel_1_mt_9,
  nivel_2_mt_9,
  nivel_3_mt_9,
  nivel_4_mt_9,
  nivel_5_mt_9,
  nivel_6_mt_9,
  nivel_7_mt_9,
  nivel_8_mt_9,
  nivel_9_mt_9
  FROM 
  `projeto-basedosdados-fl.tabelas.saeb_mu_2021`
  WHERE localizacao = 'Total'

  UNION ALL

  (SELECT 
  ano,
  id_municipio,
  rede,
  localizacao,
  media_lp_5,
  media_mt_5,
  media_lp_9,
  media_mt_9,
  media_lp_3 AS media_lp_em,
  media_mt_3 AS media_mt_em,
  nivel_0_lp_5,
  nivel_1_lp_5,
  nivel_2_lp_5,
  nivel_3_lp_5,
  nivel_4_lp_5,
  nivel_5_lp_5,
  nivel_6_lp_5,
  nivel_7_lp_5,
  nivel_8_lp_5,
  nivel_9_lp_5,
  nivel_0_mt_5,
  nivel_1_mt_5,
  nivel_2_mt_5,
  nivel_3_mt_5,
  nivel_4_mt_5,
  nivel_5_mt_5,
  nivel_6_mt_5,
  nivel_7_mt_5,
  nivel_8_mt_5,
  nivel_9_mt_5,
  nivel_10_mt_5,
  nivel_0_lp_9,
  nivel_1_lp_9,
  nivel_2_lp_9,
  nivel_3_lp_9,
  nivel_4_lp_9,
  nivel_5_lp_9,
  nivel_6_lp_9,
  nivel_7_lp_9,
  nivel_8_lp_9,
  nivel_0_mt_9,
  nivel_1_mt_9,
  nivel_2_mt_9,
  nivel_3_mt_9,
  nivel_4_mt_9,
  nivel_5_mt_9,
  nivel_6_mt_9,
  nivel_7_mt_9,
  nivel_8_mt_9,
  nivel_9_mt_9,
  FROM (
  SELECT * FROM (
  (WITH saeb AS (
  SELECT
  ano, 
  id_municipio,
  disciplina, 
  peso_aluno,
  CASE
  WHEN serie = 2 THEN 2
  WHEN serie = 5 THEN 5
  WHEN serie = 9 THEN 9
  WHEN serie = 3 THEN 3
  END AS serie,
  CASE
  WHEN rede = '1' THEN 'Federal'
  WHEN rede = '2' THEN 'Estadual'
  WHEN rede = '3' THEN 'Municipal'
  WHEN rede = '4' THEN 'Privada'
  END AS rede,
  'Total' AS localizacao,
  proficiencia_saeb,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb < 650) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb < 125) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb < 200) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb < 650) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb < 125) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb < 200) THEN 1
  ELSE 0
  END AS nivel_0,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 650 AND proficiencia_saeb < 675) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 125 AND proficiencia_saeb < 150) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 200 AND proficiencia_saeb < 225) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 650 AND proficiencia_saeb < 675) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 125 AND proficiencia_saeb < 150) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 200 AND proficiencia_saeb < 225) THEN 1
  ELSE 0
  END AS nivel_1,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 675 AND proficiencia_saeb < 700) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 150 AND proficiencia_saeb < 175) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 225 AND proficiencia_saeb < 250) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 675 AND proficiencia_saeb < 700) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 150 AND proficiencia_saeb < 175) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 225 AND proficiencia_saeb < 250) THEN 1
  ELSE 0
  END AS nivel_2,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 700 AND proficiencia_saeb < 725) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 175 AND proficiencia_saeb < 200) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 250 AND proficiencia_saeb < 275) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 700 AND proficiencia_saeb < 725) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 175 AND proficiencia_saeb < 200) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 250 AND proficiencia_saeb < 275) THEN 1
  ELSE 0
  END AS nivel_3,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 725 AND proficiencia_saeb < 750) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 200 AND proficiencia_saeb < 225) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 275 AND proficiencia_saeb < 300) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 725 AND proficiencia_saeb < 750) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 200 AND proficiencia_saeb < 225) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 275 AND proficiencia_saeb < 300) THEN 1
  ELSE 0
  END AS nivel_4,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 750 AND proficiencia_saeb < 775) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 225 AND proficiencia_saeb < 250) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 300 AND proficiencia_saeb < 325) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 750 AND proficiencia_saeb < 775) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 225 AND proficiencia_saeb < 250) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 300 AND proficiencia_saeb < 325) THEN 1
  ELSE 0
  END AS nivel_5,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 775 AND proficiencia_saeb < 800) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 250 AND proficiencia_saeb < 275) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 325 AND proficiencia_saeb < 350) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 775 AND proficiencia_saeb < 800) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 250 AND proficiencia_saeb < 275) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 325 AND proficiencia_saeb < 350) THEN 1
  ELSE 0
  END AS nivel_6,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 800 AND proficiencia_saeb < 825) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 275 AND proficiencia_saeb < 300) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 350 AND proficiencia_saeb < 375) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 800 AND proficiencia_saeb < 825) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 275 AND proficiencia_saeb < 300) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 350 AND proficiencia_saeb < 375) THEN 1
  ELSE 0
  END AS nivel_7,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 825) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 300 AND proficiencia_saeb < 325) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 375) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 825) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 300 AND proficiencia_saeb < 325) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 375 AND proficiencia_saeb < 400) THEN 1
  ELSE 0
  END AS nivel_8,
  CASE
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 325) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 325 AND proficiencia_saeb < 350) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 400) THEN 1
  ELSE 0
  END AS nivel_9,
  CASE
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 350) THEN 1
  ELSE 0
  END AS nivel_10,
  FROM `basedosdados.br_inep_saeb.proficiencia`
  WHERE ano >= 2011
  )
  SELECT 
  ano, 
  id_municipio,
  rede,
  localizacao, 
  serie,
  disciplina,
  SUM (proficiencia_saeb * peso_aluno)/ SUM (peso_aluno) AS media,
  100 * SUM(nivel_0 * peso_aluno) / SUM(peso_aluno) as nivel_0,
  100 * SUM(nivel_1 * peso_aluno) / SUM(peso_aluno) as nivel_1,
  100 * SUM(nivel_2 * peso_aluno) / SUM(peso_aluno) as nivel_2,
  100 * SUM(nivel_3 * peso_aluno) / SUM(peso_aluno) as nivel_3,
  100 * SUM(nivel_4 * peso_aluno) / SUM(peso_aluno) as nivel_4,
  100 * SUM(nivel_5 * peso_aluno) / SUM(peso_aluno) as nivel_5,
  100 * SUM(nivel_6 * peso_aluno) / SUM(peso_aluno) as nivel_6,
  100 * SUM(nivel_7 * peso_aluno) / SUM(peso_aluno) as nivel_7,
  100 * SUM(nivel_8 * peso_aluno) / SUM(peso_aluno) as nivel_8,
  100 * SUM(nivel_9 * peso_aluno) / SUM(peso_aluno) as nivel_9,
  100 * SUM(nivel_10 * peso_aluno) / SUM(peso_aluno) as nivel_10

  FROM saeb
  GROUP BY ano, rede, localizacao, serie, disciplina, id_municipio
  )

  UNION ALL

  (WITH saeb AS (
  SELECT
  ano, 
  id_municipio,
  disciplina, 
  peso_aluno,
  CASE
  WHEN serie = 2 THEN 2
  WHEN serie = 5 THEN 5
  WHEN serie = 9 THEN 9
  WHEN serie = 3 THEN 3
  END AS serie,
  CASE
  WHEN rede = '1' OR rede = '2' OR rede = '3' OR rede = '4' THEN 'Total - Federal, Estadual, Municipal e Privada'
  END AS rede,
  'Total' AS localizacao,
  proficiencia_saeb,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb < 650) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb < 125) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb < 200) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb < 650) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb < 125) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb < 200) THEN 1
  ELSE 0
  END AS nivel_0,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 650 AND proficiencia_saeb < 675) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 125 AND proficiencia_saeb < 150) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 200 AND proficiencia_saeb < 225) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 650 AND proficiencia_saeb < 675) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 125 AND proficiencia_saeb < 150) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 200 AND proficiencia_saeb < 225) THEN 1
  ELSE 0
  END AS nivel_1,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 675 AND proficiencia_saeb < 700) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 150 AND proficiencia_saeb < 175) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 225 AND proficiencia_saeb < 250) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 675 AND proficiencia_saeb < 700) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 150 AND proficiencia_saeb < 175) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 225 AND proficiencia_saeb < 250) THEN 1
  ELSE 0
  END AS nivel_2,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 700 AND proficiencia_saeb < 725) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 175 AND proficiencia_saeb < 200) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 250 AND proficiencia_saeb < 275) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 700 AND proficiencia_saeb < 725) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 175 AND proficiencia_saeb < 200) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 250 AND proficiencia_saeb < 275) THEN 1
  ELSE 0
  END AS nivel_3,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 725 AND proficiencia_saeb < 750) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 200 AND proficiencia_saeb < 225) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 275 AND proficiencia_saeb < 300) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 725 AND proficiencia_saeb < 750) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 200 AND proficiencia_saeb < 225) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 275 AND proficiencia_saeb < 300) THEN 1
  ELSE 0
  END AS nivel_4,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 750 AND proficiencia_saeb < 775) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 225 AND proficiencia_saeb < 250) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 300 AND proficiencia_saeb < 325) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 750 AND proficiencia_saeb < 775) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 225 AND proficiencia_saeb < 250) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 300 AND proficiencia_saeb < 325) THEN 1
  ELSE 0
  END AS nivel_5,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 775 AND proficiencia_saeb < 800) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 250 AND proficiencia_saeb < 275) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 325 AND proficiencia_saeb < 350) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 775 AND proficiencia_saeb < 800) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 250 AND proficiencia_saeb < 275) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 325 AND proficiencia_saeb < 350) THEN 1
  ELSE 0
  END AS nivel_6,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 800 AND proficiencia_saeb < 825) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 275 AND proficiencia_saeb < 300) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 350 AND proficiencia_saeb < 375) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 800 AND proficiencia_saeb < 825) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 275 AND proficiencia_saeb < 300) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 350 AND proficiencia_saeb < 375) THEN 1
  ELSE 0
  END AS nivel_7,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 825) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 300 AND proficiencia_saeb < 325) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 375) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 825) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 300 AND proficiencia_saeb < 325) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 375 AND proficiencia_saeb < 400) THEN 1
  ELSE 0
  END AS nivel_8,
  CASE
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 325) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 325 AND proficiencia_saeb < 350) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 400) THEN 1
  ELSE 0
  END AS nivel_9,
  CASE
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 350) THEN 1
  ELSE 0
  END AS nivel_10,
  FROM `basedosdados.br_inep_saeb.proficiencia`
  WHERE ano >= 2011
  )
  SELECT 
  ano,
  id_municipio, 
  rede,
  localizacao, 
  serie,
  disciplina,
  SUM (proficiencia_saeb * peso_aluno)/ SUM (peso_aluno) AS media,
  100 * SUM(nivel_0 * peso_aluno) / SUM(peso_aluno) as nivel_0,
  100 * SUM(nivel_1 * peso_aluno) / SUM(peso_aluno) as nivel_1,
  100 * SUM(nivel_2 * peso_aluno) / SUM(peso_aluno) as nivel_2,
  100 * SUM(nivel_3 * peso_aluno) / SUM(peso_aluno) as nivel_3,
  100 * SUM(nivel_4 * peso_aluno) / SUM(peso_aluno) as nivel_4,
  100 * SUM(nivel_5 * peso_aluno) / SUM(peso_aluno) as nivel_5,
  100 * SUM(nivel_6 * peso_aluno) / SUM(peso_aluno) as nivel_6,
  100 * SUM(nivel_7 * peso_aluno) / SUM(peso_aluno) as nivel_7,
  100 * SUM(nivel_8 * peso_aluno) / SUM(peso_aluno) as nivel_8,
  100 * SUM(nivel_9 * peso_aluno) / SUM(peso_aluno) as nivel_9,
  100 * SUM(nivel_10 * peso_aluno) / SUM(peso_aluno) as nivel_10

  FROM saeb
  GROUP BY ano, rede, localizacao, serie, disciplina, id_municipio
  )

  UNION ALL

  (WITH saeb AS (
  SELECT
  ano, 
  id_municipio,
  disciplina, 
  peso_aluno,
  CASE
  WHEN serie = 2 THEN 2
  WHEN serie = 5 THEN 5
  WHEN serie = 9 THEN 9
  WHEN serie = 3 THEN 3
  END AS serie,
  CASE
  WHEN rede = '1' OR rede = '2' OR rede = '3' THEN 'Total - Federal, Estadual e Municipal'
  END AS rede,
  'Total' AS localizacao,
  proficiencia_saeb,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb < 650) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb < 125) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb < 200) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb < 650) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb < 125) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb < 200) THEN 1
  ELSE 0
  END AS nivel_0,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 650 AND proficiencia_saeb < 675) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 125 AND proficiencia_saeb < 150) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 200 AND proficiencia_saeb < 225) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 650 AND proficiencia_saeb < 675) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 125 AND proficiencia_saeb < 150) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 200 AND proficiencia_saeb < 225) THEN 1
  ELSE 0
  END AS nivel_1,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 675 AND proficiencia_saeb < 700) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 150 AND proficiencia_saeb < 175) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 225 AND proficiencia_saeb < 250) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 675 AND proficiencia_saeb < 700) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 150 AND proficiencia_saeb < 175) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 225 AND proficiencia_saeb < 250) THEN 1
  ELSE 0
  END AS nivel_2,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 700 AND proficiencia_saeb < 725) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 175 AND proficiencia_saeb < 200) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 250 AND proficiencia_saeb < 275) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 700 AND proficiencia_saeb < 725) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 175 AND proficiencia_saeb < 200) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 250 AND proficiencia_saeb < 275) THEN 1
  ELSE 0
  END AS nivel_3,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 725 AND proficiencia_saeb < 750) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 200 AND proficiencia_saeb < 225) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 275 AND proficiencia_saeb < 300) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 725 AND proficiencia_saeb < 750) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 200 AND proficiencia_saeb < 225) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 275 AND proficiencia_saeb < 300) THEN 1
  ELSE 0
  END AS nivel_4,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 750 AND proficiencia_saeb < 775) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 225 AND proficiencia_saeb < 250) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 300 AND proficiencia_saeb < 325) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 750 AND proficiencia_saeb < 775) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 225 AND proficiencia_saeb < 250) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 300 AND proficiencia_saeb < 325) THEN 1
  ELSE 0
  END AS nivel_5,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 775 AND proficiencia_saeb < 800) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 250 AND proficiencia_saeb < 275) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 325 AND proficiencia_saeb < 350) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 775 AND proficiencia_saeb < 800) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 250 AND proficiencia_saeb < 275) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 325 AND proficiencia_saeb < 350) THEN 1
  ELSE 0
  END AS nivel_6,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 800 AND proficiencia_saeb < 825) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 275 AND proficiencia_saeb < 300) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 350 AND proficiencia_saeb < 375) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 800 AND proficiencia_saeb < 825) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 275 AND proficiencia_saeb < 300) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 350 AND proficiencia_saeb < 375) THEN 1
  ELSE 0
  END AS nivel_7,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 825) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 300 AND proficiencia_saeb < 325) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 375) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 825) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 300 AND proficiencia_saeb < 325) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 375 AND proficiencia_saeb < 400) THEN 1
  ELSE 0
  END AS nivel_8,
  CASE
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 325) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 325 AND proficiencia_saeb < 350) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 400) THEN 1
  ELSE 0
  END AS nivel_9,
  CASE
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 350) THEN 1
  ELSE 0
  END AS nivel_10,
  FROM `basedosdados.br_inep_saeb.proficiencia`
  WHERE ano >= 2011
  )
  SELECT 
  ano, 
  id_municipio,
  rede,
  localizacao, 
  serie,
  disciplina,
  SUM (proficiencia_saeb * peso_aluno)/ SUM (peso_aluno) AS media,
  100 * SUM(nivel_0 * peso_aluno) / SUM(peso_aluno) as nivel_0,
  100 * SUM(nivel_1 * peso_aluno) / SUM(peso_aluno) as nivel_1,
  100 * SUM(nivel_2 * peso_aluno) / SUM(peso_aluno) as nivel_2,
  100 * SUM(nivel_3 * peso_aluno) / SUM(peso_aluno) as nivel_3,
  100 * SUM(nivel_4 * peso_aluno) / SUM(peso_aluno) as nivel_4,
  100 * SUM(nivel_5 * peso_aluno) / SUM(peso_aluno) as nivel_5,
  100 * SUM(nivel_6 * peso_aluno) / SUM(peso_aluno) as nivel_6,
  100 * SUM(nivel_7 * peso_aluno) / SUM(peso_aluno) as nivel_7,
  100 * SUM(nivel_8 * peso_aluno) / SUM(peso_aluno) as nivel_8,
  100 * SUM(nivel_9 * peso_aluno) / SUM(peso_aluno) as nivel_9,
  100 * SUM(nivel_10 * peso_aluno) / SUM(peso_aluno) as nivel_10

  FROM saeb
  GROUP BY ano, rede, localizacao, serie, disciplina, id_municipio
  )

  UNION ALL

  (WITH saeb AS (
  SELECT
  ano, 
  id_municipio,
  disciplina, 
  peso_aluno,
  CASE
  WHEN serie = 2 THEN 2
  WHEN serie = 5 THEN 5
  WHEN serie = 9 THEN 9
  WHEN serie = 3 THEN 3
  END AS serie,
  CASE
  WHEN rede = '2' OR rede = '3' THEN 'Total - Estadual e Municipal'
  END AS rede,
  'Total' AS localizacao,
  proficiencia_saeb,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb < 650) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb < 125) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb < 200) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb < 650) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb < 125) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb < 200) THEN 1
  ELSE 0
  END AS nivel_0,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 650 AND proficiencia_saeb < 675) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 125 AND proficiencia_saeb < 150) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 200 AND proficiencia_saeb < 225) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 650 AND proficiencia_saeb < 675) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 125 AND proficiencia_saeb < 150) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 200 AND proficiencia_saeb < 225) THEN 1
  ELSE 0
  END AS nivel_1,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 675 AND proficiencia_saeb < 700) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 150 AND proficiencia_saeb < 175) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 225 AND proficiencia_saeb < 250) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 675 AND proficiencia_saeb < 700) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 150 AND proficiencia_saeb < 175) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 225 AND proficiencia_saeb < 250) THEN 1
  ELSE 0
  END AS nivel_2,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 700 AND proficiencia_saeb < 725) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 175 AND proficiencia_saeb < 200) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 250 AND proficiencia_saeb < 275) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 700 AND proficiencia_saeb < 725) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 175 AND proficiencia_saeb < 200) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 250 AND proficiencia_saeb < 275) THEN 1
  ELSE 0
  END AS nivel_3,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 725 AND proficiencia_saeb < 750) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 200 AND proficiencia_saeb < 225) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 275 AND proficiencia_saeb < 300) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 725 AND proficiencia_saeb < 750) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 200 AND proficiencia_saeb < 225) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 275 AND proficiencia_saeb < 300) THEN 1
  ELSE 0
  END AS nivel_4,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 750 AND proficiencia_saeb < 775) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 225 AND proficiencia_saeb < 250) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 300 AND proficiencia_saeb < 325) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 750 AND proficiencia_saeb < 775) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 225 AND proficiencia_saeb < 250) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 300 AND proficiencia_saeb < 325) THEN 1
  ELSE 0
  END AS nivel_5,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 775 AND proficiencia_saeb < 800) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 250 AND proficiencia_saeb < 275) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 325 AND proficiencia_saeb < 350) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 775 AND proficiencia_saeb < 800) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 250 AND proficiencia_saeb < 275) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 325 AND proficiencia_saeb < 350) THEN 1
  ELSE 0
  END AS nivel_6,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 800 AND proficiencia_saeb < 825) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 275 AND proficiencia_saeb < 300) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 350 AND proficiencia_saeb < 375) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 800 AND proficiencia_saeb < 825) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 275 AND proficiencia_saeb < 300) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 350 AND proficiencia_saeb < 375) THEN 1
  ELSE 0
  END AS nivel_7,
  CASE
  WHEN (serie = 2 AND disciplina = 'LP' AND proficiencia_saeb >= 825) THEN 1
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 300 AND proficiencia_saeb < 325) THEN 1
  WHEN (serie = 9 AND disciplina = 'LP' AND proficiencia_saeb >= 375) THEN 1
  WHEN (serie = 2 AND disciplina = 'MT' AND proficiencia_saeb >= 825) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 300 AND proficiencia_saeb < 325) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 375 AND proficiencia_saeb < 400) THEN 1
  ELSE 0
  END AS nivel_8,
  CASE
  WHEN (serie = 5 AND disciplina = 'LP' AND proficiencia_saeb >= 325) THEN 1
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 325 AND proficiencia_saeb < 350) THEN 1
  WHEN (serie = 9 AND disciplina = 'MT' AND proficiencia_saeb >= 400) THEN 1
  ELSE 0
  END AS nivel_9,
  CASE
  WHEN (serie = 5 AND disciplina = 'MT' AND proficiencia_saeb >= 350) THEN 1
  ELSE 0
  END AS nivel_10,
  FROM `basedosdados.br_inep_saeb.proficiencia`
  WHERE ano >= 2011
  )
  SELECT 
  ano,
  id_municipio,
  rede,
  localizacao, 
  serie,
  disciplina,
  SUM (proficiencia_saeb * peso_aluno)/ SUM (peso_aluno) AS media,
  100 * SUM(nivel_0 * peso_aluno) / SUM(peso_aluno) as nivel_0,
  100 * SUM(nivel_1 * peso_aluno) / SUM(peso_aluno) as nivel_1,
  100 * SUM(nivel_2 * peso_aluno) / SUM(peso_aluno) as nivel_2,
  100 * SUM(nivel_3 * peso_aluno) / SUM(peso_aluno) as nivel_3,
  100 * SUM(nivel_4 * peso_aluno) / SUM(peso_aluno) as nivel_4,
  100 * SUM(nivel_5 * peso_aluno) / SUM(peso_aluno) as nivel_5,
  100 * SUM(nivel_6 * peso_aluno) / SUM(peso_aluno) as nivel_6,
  100 * SUM(nivel_7 * peso_aluno) / SUM(peso_aluno) as nivel_7,
  100 * SUM(nivel_8 * peso_aluno) / SUM(peso_aluno) as nivel_8,
  100 * SUM(nivel_9 * peso_aluno) / SUM(peso_aluno) as nivel_9,
  100 * SUM(nivel_10 * peso_aluno) / SUM(peso_aluno) as nivel_10

  FROM saeb
  GROUP BY ano, rede, localizacao, serie, disciplina, id_municipio
  ))
  PIVOT (
  MAX (media) AS media,
  MAX (nivel_0) AS nivel_0,
  MAX (nivel_1) AS nivel_1,
  MAX (nivel_2) AS nivel_2,
  MAX (nivel_3) AS nivel_3,
  MAX (nivel_4) AS nivel_4,
  MAX (nivel_5) AS nivel_5,
  MAX (nivel_6) AS nivel_6,
  MAX (nivel_7) AS nivel_7,
  MAX (nivel_8) AS nivel_8,
  MAX (nivel_9) AS nivel_9,
  MAX (nivel_10) AS nivel_10
  FOR disciplina IN
  ('LP', 'MT')
  )
  )
  PIVOT (
  MAX (media_LP) AS media_LP,
  MAX (media_MT) AS media_MT,
  MAX (nivel_0_LP) AS nivel_0_LP,
  MAX (nivel_1_LP) AS nivel_1_LP,
  MAX (nivel_2_LP) AS nivel_2_LP,
  MAX (nivel_3_LP) AS nivel_3_LP,
  MAX (nivel_4_LP) AS nivel_4_LP,
  MAX (nivel_5_LP) AS nivel_5_LP,
  MAX (nivel_6_LP) AS nivel_6_LP,
  MAX (nivel_7_LP) AS nivel_7_LP,
  MAX (nivel_8_LP) AS nivel_8_LP,
  MAX (nivel_9_LP) AS nivel_9_LP,
  MAX (nivel_10_LP) AS nivel_10_LP,
  MAX (nivel_0_MT) AS nivel_0_MT,
  MAX (nivel_1_MT) AS nivel_1_MT,
  MAX (nivel_2_MT) AS nivel_2_MT,
  MAX (nivel_3_MT) AS nivel_3_MT,
  MAX (nivel_4_MT) AS nivel_4_MT,
  MAX (nivel_5_MT) AS nivel_5_MT,
  MAX (nivel_6_MT) AS nivel_6_MT,
  MAX (nivel_7_MT) AS nivel_7_MT,
  MAX (nivel_8_MT) AS nivel_8_MT,
  MAX (nivel_9_MT) AS nivel_9_MT,
  MAX (nivel_10_MT) AS nivel_10_MT
  FOR serie IN
  (2,5,9,3)
  )
  WHERE rede IS NOT NULL AND SUBSTR(id_municipio, 1, 1) != '6'
  ORDER BY ano, id_municipio, rede, localizacao)
)

SELECT 
    saeb.*,
    programa as programa_FL,
    ano_entrada as ano_entrada_FL ,
    interseccao as interseccao_FL,
FROM saeb
LEFT JOIN `projeto-basedosdados-fl.tabelas.br_fundacao_lemann_fundamental_2_programa_rede` 
ON SAFE_CAST(id_rede AS string) = id_municipio
WHERE ano != 2021'''

saeb_municipio = bd.read_sql(query, billing_project_id='')

In [ ]:
query2 = '''
SELECT * FROM `basedosdados.br_bd_diretorios_brasil.municipio`
'''
municipio = bd.read_sql(query2, billing_project_id='pisagab-staging')
municipio = municipio[['id_municipio', 'sigla_uf']]

In [4]:
#corrige problema no erro de preenchimento da categoria de rede
saeb_municipio['rede'] = saeb_municipio['rede'].replace('total -federal, estadual, municipal e privada', 'total - federal, estadual, municipal e privada')

#so em 2021 diferencia tipos de ensino medio, para compatibilizar com a série existênte a diferença será desconsiderada.
saeb_municipio = saeb_municipio[saeb_municipio['serie'] != 12]
saeb_municipio = saeb_municipio[saeb_municipio['serie'] != 13]

In [16]:
#importa dados do saeb baixados do ibge
saeb_mu = pd.read_excel(r'saeb_2021_brasil_estados_municipios.xlsx', dtype=str, sheet_name='Municípios')
saeb_mu.drop(0, axis=0, inplace=True)

In [18]:
#captura toda base

rename = {'ANO_SAEB': 'ano',
          'CO_MUNICIPIO' :'id_municipio',
          'NO_UF' : 'sigla_uf',
          'DEPENDENCIA_ADM':'rede', 
          'LOCALIZACAO':'localizacao', 
          'CAPITAL':'capital',
          'MEDIA_5_LP':'media_lp_5',
          'MEDIA_5_MT':'media_mt_5', 
          'MEDIA_9_LP':'media_lp_9', 
          'MEDIA_9_MT':'media_mt_9', 
          'MEDIA_12_LP':'media_lp_em', 
          'MEDIA_12_MT':'media_mt_em',
          'MEDIA_13_LP':'media_lp_em_integral',
          'MEDIA_13_MT':'media_mt_em_integral',
          'MEDIA_14_LP':'media_lp_em_regular',
          'MEDIA_14_MT':'media_mt_em_regular',
          'nivel_0_LP5':'nivel_0_lp_5', 
          'nivel_1_LP5':'nivel_1_lp_5', 
          'nivel_2_LP5':'nivel_2_lp_5', 
          'nivel_3_LP5':'nivel_3_lp_5',
          'nivel_4_LP5':'nivel_4_lp_5', 
          'nivel_5_LP5':'nivel_5_lp_5', 
          'nivel_6_LP5':'nivel_6_lp_5', 
          'nivel_7_LP5':'nivel_7_lp_5',
          'nivel_8_LP5':'nivel_8_lp_5', 
          'nivel_9_LP5':'nivel_9_lp_5', 
          'nivel_0_MT5':'nivel_0_mt_5', 
          'nivel_1_MT5':'nivel_1_mt_5',
          'nivel_2_MT5':'nivel_2_mt_5', 
          'nivel_3_MT5':'nivel_3_mt_5', 
          'nivel_4_MT5':'nivel_4_mt_5', 
          'nivel_5_MT5':'nivel_5_mt_5',
          'nivel_6_MT5':'nivel_6_mt_5', 
          'nivel_7_MT5':'nivel_7_mt_5', 
          'nivel_8_MT5':'nivel_8_mt_5', 
          'nivel_9_MT5':'nivel_9_mt_5',
          'nivel_10_MT5':'nivel_10_mt_5', 
          'nivel_0_LP9':'nivel_0_lp_9', 
          'nivel_1_LP9':'nivel_1_lp_9', 
          'nivel_2_LP9':'nivel_2_lp_9',
          'nivel_3_LP9':'nivel_3_lp_9', 
          'nivel_4_LP9':'nivel_4_lp_9', 
          'nivel_5_LP9':'nivel_5_lp_9', 
          'nivel_6_LP9':'nivel_6_lp_9',
          'nivel_7_LP9':'nivel_7_lp_9', 
          'nivel_8_LP9':'nivel_8_lp_9', 
          'nivel_0_MT9':'nivel_0_mt_9', 
          'nivel_1_MT9':'nivel_1_mt_9',
          'nivel_2_MT9':'nivel_2_mt_9', 
          'nivel_3_MT9':'nivel_3_mt_9', 
          'nivel_4_MT9':'nivel_4_mt_9', 
          'nivel_5_MT9':'nivel_5_mt_9',
          'nivel_6_MT9':'nivel_6_mt_9', 
          'nivel_7_MT9':'nivel_7_mt_9', 
          'nivel_8_MT9':'nivel_8_mt_9', 
          'nivel_9_MT9':'nivel_9_mt_9',
          'nivel_0_LP12':'nivel_0_lp_em', 
          'nivel_1_LP12':'nivel_1_lp_em', 
          'nivel_2_LP12':'nivel_2_lp_em', 
          'nivel_3_LP12':'nivel_3_lp_em',
          'nivel_4_LP12':'nivel_4_lp_em', 
          'nivel_5_LP12':'nivel_5_lp_em', 
          'nivel_6_LP12':'nivel_6_lp_em', 
          'nivel_7_LP12':'nivel_7_lp_em',
          'nivel_8_LP12':'nivel_8_lp_em', 
          'nivel_0_MT12':'nivel_0_mt_em', 
          'nivel_1_MT12':'nivel_1_mt_em', 
          'nivel_2_MT12':'nivel_2_mt_em',
          'nivel_3_MT12':'nivel_3_mt_em', 
          'nivel_4_MT12':'nivel_4_mt_em', 
          'nivel_5_MT12':'nivel_5_mt_em', 
          'nivel_6_MT12':'nivel_6_mt_em',
          'nivel_7_MT12':'nivel_7_mt_em', 
          'nivel_8_MT12':'nivel_8_mt_em', 
          'nivel_9_MT12':'nivel_9_mt_em', 
          'nivel_10_MT12':'nivel_10_mt_em',
          'nivel_0_LP13':'nivel_0_lp_em_integral', 
          'nivel_1_LP13':'nivel_1_lp_em_integral', 
          'nivel_2_LP13':'nivel_2_lp_em_integral', 
          'nivel_3_LP13':'nivel_3_lp_em_integral',
          'nivel_4_LP13':'nivel_4_lp_em_integral', 
          'nivel_5_LP13':'nivel_5_lp_em_integral', 
          'nivel_6_LP13':'nivel_6_lp_em_integral', 
          'nivel_7_LP13':'nivel_7_lp_em_integral',
          'nivel_8_LP13':'nivel_8_lp_em_integral', 
          'nivel_0_MT13':'nivel_0_mt_em_integral', 
          'nivel_1_MT13':'nivel_1_mt_em_integral', 
          'nivel_2_MT13':'nivel_2_mt_em_integral',
          'nivel_3_MT13':'nivel_3_mt_em_integral', 
          'nivel_4_MT13':'nivel_4_mt_em_integral', 
          'nivel_5_MT13':'nivel_5_mt_em_integral', 
          'nivel_6_MT13':'nivel_6_mt_em_integral',
          'nivel_7_MT13':'nivel_7_mt_em_integral', 
          'nivel_8_MT13':'nivel_8_mt_em_integral', 
          'nivel_9_MT13':'nivel_9_mt_em_integral', 
          'nivel_10_MT13':'nivel_10_mt_em_integral',
          'nivel_0_LP14':'nivel_0_lp_em_regular', 
          'nivel_1_LP14':'nivel_1_lp_em_regular', 
          'nivel_2_LP14':'nivel_2_lp_em_regular', 
          'nivel_3_LP14':'nivel_3_lp_em_regular',
          'nivel_4_LP14':'nivel_4_lp_em_regular', 
          'nivel_5_LP14':'nivel_5_lp_em_regular', 
          'nivel_6_LP14':'nivel_6_lp_em_regular', 
          'nivel_7_LP14':'nivel_7_lp_em_regular',
          'nivel_8_LP14':'nivel_8_lp_em_regular', 
          'nivel_0_MT14':'nivel_0_mt_em_regular', 
          'nivel_1_MT14':'nivel_1_mt_em_regular', 
          'nivel_2_MT14':'nivel_2_mt_em_regular',
          'nivel_3_MT14':'nivel_3_mt_em_regular', 
          'nivel_4_MT14':'nivel_4_mt_em_regular', 
          'nivel_5_MT14':'nivel_5_mt_em_regular', 
          'nivel_6_MT14':'nivel_6_mt_em_regular',
          'nivel_7_MT14':'nivel_7_mt_em_regular', 
          'nivel_8_MT14':'nivel_8_mt_em_regular', 
          'nivel_9_MT14':'nivel_9_mt_em_regular', 
          'nivel_10_MT14':'nivel_10_mt_em_regular'}

saeb_mu.rename(columns=rename, inplace=True)

In [ ]:

#seleciona as variáveis por disciplina e série {materia}_{serie}
ordem_colunas = ['ano', 'rede', 'localizacao', 'sigla_uf', 'id_municipio',
       'disciplina', 'serie', 'media', 'nivel_0', 'nivel_1', 'nivel_2',
       'nivel_3', 'nivel_4', 'nivel_5', 'nivel_6', 'nivel_7', 'nivel_8',
       'nivel_9', 'nivel_10']
#? lista com series
# ! Para as avaliações de lp não existem niveis 9 e 10. O nivel de LP só vai até 8 para em
l_series = [
            'em','5','9'
            ]
#? lista com materias
l_materias = [  
              'mt','lp' 
              ]
#? lista vazia para armazenar dados
data2021 = []
#em e 5 mt
#9 mt
#5 lp
#9 ee m lp
#? para cada serie
for serie in l_series:
    #? para cada materia
    for materia in l_materias:


            #mt em ano ate 10 criar nada
            #mt 5 ano ate 10 criar nada  
        if  materia == 'mt' and (serie == '5' or serie =='em'): 
            print(f'fazendo serie_{serie} e materia_{materia}')
            #? extrai dados da planilha do ibge, de uma materia de uma serie
            data = saeb_mu[['ano', 'rede' ,'localizacao' ,'id_municipio','sigla_uf',
                  f'media_{materia}_{serie}',  
                  f'nivel_0_{materia}_{serie}', 
                  f'nivel_1_{materia}_{serie}', 
                  f'nivel_2_{materia}_{serie}', 
                  f'nivel_3_{materia}_{serie}', 
                  f'nivel_4_{materia}_{serie}', 
                  f'nivel_5_{materia}_{serie}',
                  f'nivel_6_{materia}_{serie}', 
                  f'nivel_7_{materia}_{serie}', 
                  f'nivel_8_{materia}_{serie}', 
                  f'nivel_9_{materia}_{serie}', 
                  f'nivel_10_{materia}_{serie}']]
            

        elif materia == 'mt' and serie == '9':
        #mt 9 ano ate 9 criar nivel_10_mt_9
            print(f'fazendo serie_{serie} e materia_{materia}')
            #? extrai dados da planilha do ibge, de uma materia de uma serie
            data = saeb_mu[['ano', 'rede' ,'localizacao' ,'id_municipio','sigla_uf',
                    f'media_{materia}_{serie}',  
                    f'nivel_0_{materia}_{serie}', 
                    f'nivel_1_{materia}_{serie}', 
                    f'nivel_2_{materia}_{serie}', 
                    f'nivel_3_{materia}_{serie}', 
                    f'nivel_4_{materia}_{serie}', 
                    f'nivel_5_{materia}_{serie}',
                    f'nivel_6_{materia}_{serie}', 
                    f'nivel_7_{materia}_{serie}', 
                    f'nivel_8_{materia}_{serie}', 
                    f'nivel_9_{materia}_{serie}']]
           
            data[f'nivel_10_{materia}_{serie}'] = np.nan

             
        elif materia == 'lp' and serie == '5':    
        #lp 5 ano ate 9 criar  nivel_10_lp_5
            print(f'fazendo serie_{serie} e materia_{materia}')
            #? extrai dados da planilha do ibge, de uma materia de uma serie
            data = saeb_mu[['ano', 'rede' ,'localizacao' ,'id_municipio','sigla_uf',
                    f'media_{materia}_{serie}',  
                    f'nivel_0_{materia}_{serie}', 
                    f'nivel_1_{materia}_{serie}', 
                    f'nivel_2_{materia}_{serie}', 
                    f'nivel_3_{materia}_{serie}', 
                    f'nivel_4_{materia}_{serie}', 
                    f'nivel_5_{materia}_{serie}',
                    f'nivel_6_{materia}_{serie}', 
                    f'nivel_7_{materia}_{serie}', 
                    f'nivel_8_{materia}_{serie}', 
                    f'nivel_9_{materia}_{serie}']]
            
            data[f'nivel_10_{materia}_{serie}'] = np.nan


         #lp 9 ano ate 8 criar nivel_9_lp_9 nivel_10_lp_9
         #lp em ano ate 8 criar  nivel_9_lp_em nivel_10_lp_em
        
        elif materia == 'lp' and (serie == '9' or serie == 'em'):
            
            print(f'fazendo serie_{serie} e materia_{materia}')
            #? extrai dados da planilha do ibge, de uma materia de uma serie
            data = saeb_mu[['ano', 'rede' ,'localizacao' ,'id_municipio','sigla_uf',
                    f'media_{materia}_{serie}',  
                    f'nivel_0_{materia}_{serie}', 
                    f'nivel_1_{materia}_{serie}', 
                    f'nivel_2_{materia}_{serie}', 
                    f'nivel_3_{materia}_{serie}', 
                    f'nivel_4_{materia}_{serie}', 
                    f'nivel_5_{materia}_{serie}',
                    f'nivel_6_{materia}_{serie}', 
                    f'nivel_7_{materia}_{serie}', 
                    f'nivel_8_{materia}_{serie}']]
            
            data[f'nivel_9_{materia}_{serie}'] = np.nan
            data[f'nivel_10_{materia}_{serie}'] = np.nan       
            
        print(data.columns.values)
        # ? compatibilizando colunas do saeb inep com o saeb padronizado da bd
        data.rename(columns={f'media_{materia}_{serie}':'media',
                             f'nivel_0_{materia}_{serie}':'nivel_0', 
                             f'nivel_1_{materia}_{serie}':'nivel_1', 
                             f'nivel_2_{materia}_{serie}':'nivel_2',
                             f'nivel_3_{materia}_{serie}':'nivel_3',
                             f'nivel_4_{materia}_{serie}':'nivel_4', 
                             f'nivel_5_{materia}_{serie}':'nivel_5',
                             f'nivel_6_{materia}_{serie}':'nivel_6', 
                             f'nivel_7_{materia}_{serie}':'nivel_7', 
                             f'nivel_8_{materia}_{serie}':'nivel_8',
                             f'nivel_9_{materia}_{serie}':'nivel_9',
                             f'nivel_10_{materia}_{serie}':'nivel_10'},
                               inplace=True)
        
        # todo: cria variavel de disciplina
        data['disciplina'] = f'{materia}'
        data['disciplina'] = data['disciplina'].str.upper() 

        # todo: criar variavel de série (3 series: )
        data['serie'] = f'{serie}'    



          #depois é só juntar com append os saeb_mu_serie_discplina

        #trocar a serie em para 3  
        data['serie'].replace('em', '3', inplace=True)
       
        
        #ordenar colunas
        data  = data[ordem_colunas]

        data2021.append(data)
        print(f'tabela {materia}__{serie} feita!')


# ! para finalizar, dar append na serie

In [22]:
saeb_municipio = saeb_municipio.append(data2021)

In [23]:
saeb_municipio.to_csv("municipio.csv",
                            index=False,
                            sep = ',',
                            na_rep= '',
                            encoding = 'utf-8')